// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class LoginAutomationSuiteTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void invalidLoginTest() {
    driver.get("https://the-internet.herokuapp.com/login");
    driver.manage().window().setSize(new Dimension(1280, 672));
    driver.findElement(By.id("username")).sendKeys("tomsmith");
    driver.findElement(By.id("password")).sendKeys("SuperSecretPassword!");
    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).sendKeys("SuperSecretPassword!567");
    driver.findElement(By.cssSelector(".fa")).click();
    driver.findElement(By.id("flash")).click();
    driver.findElement(By.cssSelector("h2")).click();
    driver.findElement(By.cssSelector("h2")).click();
    assertThat(driver.findElement(By.cssSelector("h2")).getText(), is("Login Page"));
    driver.findElement(By.cssSelector(".subheader")).click();
    driver.findElement(By.id("flash")).click();
    assertThat(driver.findElement(By.id("flash")).getText(), is("Your password is invalid!\\\\n×"));
    driver.findElement(By.cssSelector("#login > .row:nth-child(2)")).click();
    driver.close();
  }
  @Test
  public void validLoginTest() {
    driver.get("https://the-internet.herokuapp.com/login/login");
    driver.manage().window().setSize(new Dimension(1280, 672));
    driver.findElement(By.id("password")).click();
    driver.findElement(By.cssSelector(".fa")).click();
    driver.findElement(By.cssSelector("h2")).click();
    assertThat(driver.findElement(By.cssSelector("h2")).getText(), is("Secure Area"));
    driver.findElement(By.cssSelector(".subheader")).click();
    assertThat(driver.findElement(By.cssSelector(".subheader")).getText(), is("Welcome to the Secure Area. When you are done click logout below."));
    driver.close();
  }
}
