# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestLoginAutomationSuite():
  def setup_method(self, method):
    self.driver = webdriver.Remote(command_executor='http://localhost:4444/wd/hub', desired_capabilities=DesiredCapabilities.FIREFOX)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_invalidLoginTest(self):
    # Test name: InvalidLoginTest
    # Step # | name | target | value
    # 1 | open | https://the-internet.herokuapp.com/login | 
    self.driver.get("https://the-internet.herokuapp.com/login")
    # 2 | setWindowSize | 1280x672 | 
    self.driver.set_window_size(1280, 672)
    # 3 | type | id=username | tomsmith
    self.driver.find_element(By.ID, "username").send_keys("tomsmith")
    # 4 | type | id=password | SuperSecretPassword!
    self.driver.find_element(By.ID, "password").send_keys("SuperSecretPassword!")
    # 5 | click | id=password | 
    self.driver.find_element(By.ID, "password").click()
    # 6 | type | id=password | SuperSecretPassword!567
    self.driver.find_element(By.ID, "password").send_keys("SuperSecretPassword!567")
    # 7 | click | css=.fa | 
    self.driver.find_element(By.CSS_SELECTOR, ".fa").click()
    # 8 | click | id=flash | 
    self.driver.find_element(By.ID, "flash").click()
    # 9 | click | css=h2 | 
    self.driver.find_element(By.CSS_SELECTOR, "h2").click()
    # 10 | click | css=h2 | 
    self.driver.find_element(By.CSS_SELECTOR, "h2").click()
    # 11 | assertText | css=h2 | Login Page
    assert self.driver.find_element(By.CSS_SELECTOR, "h2").text == "Login Page"
    # 12 | click | css=.subheader | 
    self.driver.find_element(By.CSS_SELECTOR, ".subheader").click()
    # 13 | click | id=flash | 
    self.driver.find_element(By.ID, "flash").click()
    # 14 | assertText | id=flash | Your password is invalid!\n×
    assert self.driver.find_element(By.ID, "flash").text == "Your password is invalid!\\\\n×"
    # 15 | click | css=#login > .row:nth-child(2) | 
    self.driver.find_element(By.CSS_SELECTOR, "#login > .row:nth-child(2)").click()
    # 16 | close |  | 
    self.driver.close()
  
  def test_validLoginTest(self):
    # Test name: ValidLoginTest
    # Step # | name | target | value
    # 1 | open | /login | 
    self.driver.get("https://the-internet.herokuapp.com/login/login")
    # 2 | setWindowSize | 1280x672 | 
    self.driver.set_window_size(1280, 672)
    # 3 | click | id=password | 
    self.driver.find_element(By.ID, "password").click()
    # 4 | click | css=.fa | 
    self.driver.find_element(By.CSS_SELECTOR, ".fa").click()
    # 5 | click | css=h2 | 
    self.driver.find_element(By.CSS_SELECTOR, "h2").click()
    # 6 | assertText | css=h2 | Secure Area
    assert self.driver.find_element(By.CSS_SELECTOR, "h2").text == "Secure Area"
    # 7 | click | css=.subheader | 
    self.driver.find_element(By.CSS_SELECTOR, ".subheader").click()
    # 8 | assertText | css=.subheader | Welcome to the Secure Area. When you are done click logout below.
    assert self.driver.find_element(By.CSS_SELECTOR, ".subheader").text == "Welcome to the Secure Area. When you are done click logout below."
    # 9 | close |  | 
    self.driver.close()
  
